# Generated by Django 3.0.3 on 2020-03-12 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('airport_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('airport_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=35)),
                ('coordinates', models.CharField(max_length=100)),
                ('timezone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('flight_no', models.PositiveIntegerField()),
                ('scheduled_departure', models.DateTimeField()),
                ('scheduled_arrival', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('aircraft_code', models.CharField(max_length=3)),
                ('actual_departure', models.DateTimeField()),
                ('actual_arrival', models.DateTimeField()),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airport', to='airtrans.Airports')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport', to='airtrans.Airports')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_no', models.AutoField(primary_key=True, serialize=False)),
                ('passenger_id', models.PositiveIntegerField()),
                ('passenger_name', models.CharField(max_length=100)),
                ('contact_data', models.CharField(max_length=100)),
                ('book_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Bookings')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_flights',
            fields=[
                ('ticket_no', models.AutoField(primary_key=True, serialize=False)),
                ('fare_conditions', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Flights')),
            ],
        ),
        migrations.CreateModel(
            name='Boarding_passes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_no', models.CharField(max_length=3)),
                ('seat_no', models.CharField(max_length=3)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Flights')),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Ticket_flights')),
            ],
            options={
                'unique_together': {('ticket_no', 'flight_id')},
            },
        ),
    ]
